version: '3.8'
services:
  db:
    image: bitnami/mysql:latest
    env_file:
      - .env
    volumes:
      - ./volumes/mysql:/bitnami/mysql/data
    networks:
      - universal
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: universal-lite
    container_name: universal-lite
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - universal
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - ${PORT}:80
    volumes:
      - ./:/var/www
      - ./src/kernel/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/kernel/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/kernel/conf/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./src/kernel/conf/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./volumes/nginx:/etc/nginx/cache
    networks:
      - universal

networks:
  universal:
    driver: bridge